# -*- coding: utf-8 -*-
"""Intelligent_AI_Agent_(Tools_+_Memory).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIs-hGpLqK7onRSY9L79iCesrmXCCIG4
"""

# Install required libraries
!pip install transformers sentence-transformers faiss-cpu wikipedia --quiet
# Import necessary libraries

from transformers import pipeline
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import wikipedia
# Load a free HuggingFace text generation model
# This model runs on GPU if available

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    device=0  # 0 = GPU, -1 = CPU
)
# Short-term memory (stores recent conversations)

short_term_memory = []

def add_to_memory(user, response):
    short_term_memory.append({"user": user, "response": response})

    # Keep only last 5 conversations
    if len(short_term_memory) > 5:
        short_term_memory.pop(0)
# Load embedding model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Create FAISS index
dimension = 384  # embedding size of model
index = faiss.IndexFlatL2(dimension)

long_term_texts = []

def add_long_term_memory(text):
    embedding = embedding_model.encode([text])
    index.add(np.array(embedding))
    long_term_texts.append(text)

def search_long_term_memory(query):
    query_embedding = embedding_model.encode([query])
    D, I = index.search(np.array(query_embedding), k=1)

    if len(long_term_texts) > 0:
        return long_term_texts[I[0][0]]
    return ""
def calculator_tool(expression):
    try:
        return str(eval(expression))
    except:
        return "Invalid calculation"

def wiki_tool(query):
    try:
        return wikipedia.summary(query, sentences=2)
    except:
        return "No information found."
def agent_reasoning(user_input):

    print("🧠 Reasoning Step:")

    # If math detected → use calculator
    if any(char.isdigit() for char in user_input):
        print("→ Detected mathematical expression. Using calculator tool.")
        return calculator_tool(user_input)

    # If user asks about 'who', 'what', etc → use wiki
    elif any(word in user_input.lower() for word in ["who", "what", "where", "when"]):
        print("→ Detected knowledge query. Using Wikipedia tool.")
        return wiki_tool(user_input)

    else:
        print("→ Using LLM for general response.")
        context = search_long_term_memory(user_input)

        prompt = f"""
        Context: {context}
        User: {user_input}
        Answer:
        """

        result = generator(prompt, max_length=200)
        return result[0]['generated_text']
def intelligent_agent(user_input):

    # Get response
    response = agent_reasoning(user_input)

    # Save in short-term memory
    add_to_memory(user_input, response)

    # Save important things to long-term memory
    add_long_term_memory(user_input + " " + response)

    return response
print(intelligent_agent("What is Artificial Intelligence?"))
print(intelligent_agent("2 + 56 * 3"))
print(intelligent_agent("Who is Elon Musk?"))
ye mere second number project hai